### ISSUE TITLE
retour

### ISSUE THREAD

**Issue by nico2che** [roptch/weglot-js-assessment#1]
j'avais tort, ton code fonctionne parfaitement, je me suis fait avoir en debug sur les tests qui n'ont pas de config à l'instanciation de Solver

Donc dans tes tests, `this._maxTime` vaut la valeur défaut, ce qui ne semble déranger personne avec ces données... 🙃

https://github.com/roptch/weglot-js-assessment/blob/089c0d2c124c6cef050c4ad7f8d1527bfa2f0d83/test/index.spec.js#L19

**Comment by roptch** [comment]
En effet il y avait peut-être un petit soucis avec la config par défaut, qui n'était bien sûr pas du tout dû à un copié-collé foireux de la ligne du dessus 🥲
Merci du retour @nico2che :)
